name_or_path: gpt2
class_name: AutoModelForCausalLM
edit_modules:
- transformer.h.6.mlp.c_proj
- transformer.h.7.mlp.c_proj
- transformer.h.8.mlp.c_proj
- transformer.h.9.mlp.c_proj
- transformer.h.10.mlp.c_proj
- transformer.h.11.mlp.c_proj
# - transformer.h.9.mlp.c_fc
# - transformer.h.10.mlp.c_fc
# - transformer.h.11.mlp.c_fc
half: False